# Generated by Django 2.1.2 on 2019-01-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lunar_Lovelies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
