# Generated by Django 2.1.2 on 2019-01-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lunar_Lovelies', '0002_auto_20190120_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='products',
        ),
    ]
